project:
  type: website
  # resources:
  #   - "images/twitter-card.png"
  #   - "course-materials/_slides/"
    
website:
  open-graph: true
  page-navigation: true
  title: "RAP Markdown"
  description: "RAP Markdown"
  # date: now
  # favicon: _assets/img/rapdown_colour.ico
  repo-url: https://github.com/craig-shenton/RAPdown
  repo-actions: [edit, issue]
  site-url: https://craig-shenton.github.io/RAPdown/

  twitter-card:
    creator: "@craigrshenton"
    image: "https://pbs.twimg.com/profile_images/800388889114451968/Ta6tqm7s_400x400.jpg"

  page-footer:
    left: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    # background: "#005eb8"
    right:
    - text: "License"
      href: https://github.com/craig-shenton/RAPdown/blob/main/LICENSE
    - text: "Code of Conduct"
      href: https://github.com/craig-shenton/RAPdown/blob/main/CODE_OF_CONDUCT.md

  navbar:
    background: light
    title: false
    collapse-below: lg
    left:
      - text: "Homepage"
        icon: "house-door"
        href: index.qmd
      - text: "Tutorials"
        icon: "bookmark-check"
        href: tutorials/index.qmd
      - text: "Documentation"
        icon: "file-earmark-text"
        href: documentation/index.qmd
      - text: "Updates"
        icon: "patch-check"
        menu:
          - text: "Blog"
            icon: "rss"
            href: blog.qmd
          - text: "0.0.1"
            icon: "code-square"
            href: posts/0.0.1/index.qmd
      - text: "Help"
        icon: "info-square"
        menu:
          - text: "Report a Bug"
            icon: "bug"
            href: "https://github.com/craig-shenton/RAPdown/issues"
          - text: "Ask a Question"
            icon: "chat-right-text"
            href: "https://github.com/craig-shenton/RAPdown/discussions"
          - text: "FAQ"
            icon: "question-circle"
            href: faq.qmd
    right:
      - text: "About"
        href: about.qmd
      - icon: box-seam
        href: https://cloud.r-project.org/web/packages/
      - icon: twitter
        href: https://twitter.com/craigrshenton
        aria-label: Twitter
      - icon: github
        href: https://github.com/craig-shenton/RAPdown
        aria-label: GitHub

  sidebar:
    id: toc-side
    style: "floating"
    pinned: true
    contents:
      - text: "Homepage" 
        file: index.qmd
      - section: Tutorials
        file: tutorials/index.qmd
        contents: 
          - auto: tutorials/*.qmd
      - section: Documentation
        file: documentation/index.qmd
        contents: 
          - auto: documentation/*.qmd
      - text: "Example Report"
        href: ae_attendance.html
      - section: Updates
        file: blog.qmd
        contents: 
          - auto: posts/*.qmd
      - text: "FAQ"
        file: faq.qmd
      - text: "About"
        file: about.qmd
      # right:
      #   - icon: github
      #     href: https://github.com/craig-shenton/RAPdown
      #     aria-label: GitHub
  comments:
    giscus:
      repo: craig-shenton/RAPdown
format:
  html:
    toc: true
    toc-depth: 4
    theme:
      light: [cosmo, _assets/style/theme.scss]
    code-copy: true
    code-overflow: wrap
    css: _assets/style/styles.css
    include-after-body: _assets/style/js.html
    # grid:
    #   sidebar-width: 250px
    #   body-width: 900px
    #   margin-width: 300px
    # # Code options
    # code-tools:
    #   source: false
    #   toggle: false
    #   caption: none
    # code-fold: true
    # code-summary: "Show code"
    # code-copy: true
    # code-overflow: wrap
